[package]
name = "lag"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"


[[bin]]
name = "client"


[dependencies]
ron = "0.8"
serde = { version = "1", features = ["derive"] }
anyhow = "1.0"

